Add-Type -AssemblyName System.Drawing
$img1 = [System.Drawing.Image]::FromFile('assets/images/logos/PNG Logo V06 Onra.png')
$rect = New-Object System.Drawing.Rectangle(0, 0, 300, 300)
$bmp1 = New-Object System.Drawing.Bitmap(300, 300)
$g1 = [System.Drawing.Graphics]::FromImage($bmp1)
$g1.DrawImage($img1, 0, 0, $rect, [System.Drawing.GraphicsUnit]::Pixel)
$bmp1.Save('assets/icons/favicon.png', [System.Drawing.Imaging.ImageFormat]::Png)
$g1.Dispose()
$bmp1.Dispose()
$img1.Dispose()

$img2 = [System.Drawing.Image]::FromFile('assets/images/logos/PNG Logo V03 Onra.png')
$bmp2 = New-Object System.Drawing.Bitmap(300, 300)
$g2 = [System.Drawing.Graphics]::FromImage($bmp2)
$g2.DrawImage($img2, 0, 0, $rect, [System.Drawing.GraphicsUnit]::Pixel)
$bmp2.Save('assets/images/logos/transition-logo.png', [System.Drawing.Imaging.ImageFormat]::Png)
$g2.Dispose()
$bmp2.Dispose()
$img2.Dispose()
